### ISSUE TITLE
multi editors

### ISSUE THREAD

**Issue by AhmedAliGad** [mayasabha/ckeditor4-vue3#8] opened 2023-08-13 13:16 UTC
how can use more than one `<ckeditor></ckeditor>` at same page

**Comment by apoorvpal01** [comment] 2023-08-15 04:29
You should be able to get two editors by just adding the component twice. This was tested on a sample Vue + Vite project

Sample Code:
```
<script setup>
import { ref } from 'vue'
import { component as ckeditor } from '@mayasabha/ckeditor4-vue3/dist/ckeditor'

const editorData = ref("test");

const editorUrl = "https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js";

const editorConfig = {
  FillEmptyBlocks: false,
  removePlugins: "image",
  language: "en",
  allowedContent: true,
  colorButton_enableMore: true,
  editorplaceholder: "type your text here",
  toolbar: [
    ["Source", "Maximize"],
    ["Format"],
    ["Bold", "Italic", "Strike"],
    ["Undo", "Redo"],
    ["RemoveFormat", "NumberedList", "BulletedList", "Outdent", "Indent"],
    ["Blockquote"],
    ["Link", "Unlink"],
    ["Table", "HorizontalRule"],
  ],
};
</script>

<template>
  <main>
    <ckeditor v-model="editorData" :editorUrl="editorUrl" :config="editorConfig" :throttle="120"></ckeditor>
    <ckeditor :editorUrl="editorUrl" :config="editorConfig" :throttle="120"></ckeditor>
  </main>
</template>
```

**Comment by AhmedAliGad** [comment] 2023-08-15 05:20
I already added two ckeditor components but when I change the content at any one it overwrites the other and be the same
`<ckeditor v-model="form.terms" :config="editorConfig"  :throttle="120"></ckeditor>`
`<ckeditor  v-model="form.description" :config="editorConfig"  :throttle="120"></ckeditor>`

**Comment by apoorvpal01** [comment] 2023-08-16 10:35
The following code has been confirmed to be working on a Vite project. Please share the full source code to replicate the issue you are facing.

```vue
<script setup>
import { ref } from 'vue'
import { component as ckeditor } from '@mayasabha/ckeditor4-vue3/dist/ckeditor'

const form = ref({
  terms: "terms",
  description: "description"
})

const editorUrl = "https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js";

const editorConfig = {
  FillEmptyBlocks: false,
  removePlugins: "image",
  language: "en",
  allowedContent: true,
  colorButton_enableMore: true,
  editorplaceholder: "type your text here",
  toolbar: [
    ["Source", "Maximize"],
    ["Format"],
    ["Bold", "Italic", "Strike"],
    ["Undo", "Redo"],
    ["RemoveFormat", "NumberedList", "BulletedList", "Outdent", "Indent"],
    ["Blockquote"],
    ["Link", "Unlink"],
    ["Table", "HorizontalRule"],
  ],
};
</script>

<template>
  <main>
    <ckeditor v-model="form.terms" :editorUrl="editorUrl" :config="editorConfig" :throttle="120"></ckeditor>
    <ckeditor v-model="form.description" :editorUrl="editorUrl" :config="editorConfig" :throttle="120"></ckeditor>
  </main>
</template>
```

![image](https://github.com/mayasabha/ckeditor4-vue3/assets/25688589/86d14b13-2d26-4790-b10e-a67e10d0eb4e)

**Comment by AhmedAliGad** [comment] 2023-08-16 11:12
`<script setup>
import { Head, useForm } from "@inertiajs/vue3"
import { mdiCogs, mdiArrowLeftBoldOutline, mdiAlertBoxOutline } from "@mdi/js"
import LayoutAuthenticated from "@/Layouts/LayoutAuthenticated.vue"
import SectionMain from "@/Components/SectionMain.vue"
import SectionTitleLineWithButton from "@/Components/SectionTitleLineWithButton.vue"
import CardBox from "@/Components/CardBox.vue"
import FormField from '@/Components/FormField.vue'
import BaseButton from '@/Components/BaseButton.vue'
import BaseButtons from '@/Components/BaseButtons.vue'
import { component as ckeditor } from '@mayasabha/ckeditor4-vue3'
import NotificationBar from "@/Components/NotificationBar.vue";
import BaseDivider from "@/Components/BaseDivider.vue";

const props = defineProps({
    setting: {
        type: Object,
        default: () => ({}),
    },
})

const editorConfig = {
    language: "en",
    filebrowserImageBrowseUrl: `/laravel-filemanager?type=Images`,
    filebrowserBrowseUrl: `/laravel-filemanager?type=Files`,
}
const form = useForm({
    _method: 'put',
    privacy_en : props.setting.privacy_en,
    terms_en : props.setting.terms_en,
})
</script>

<template>
    <LayoutAuthenticated>
        <Head title="Update Settings" />
        <SectionMain>
            <SectionTitleLineWithButton
                :icon="mdiCogs"
                title="Update App Setting"
                main
            >
                <BaseButton
                    :route-name="route('dashboard')"
                    :icon="mdiArrowLeftBoldOutline"
                    label="Back"
                    color="white"
                    rounded-full
                    small
                />
            </SectionTitleLineWithButton>
            <NotificationBar
                v-if="$page.props.flash.message"
                color="success"
                :icon="mdiAlertBoxOutline"
            >
                {{ $page.props.flash.message }}
            </NotificationBar>

            <CardBox
                form
                @submit.prevent="form.post(route('settings_update'))"
            >
                <FormField
                    label="Privacy"
                    :class="{ 'text-red-400': form.errors.privacy_en }"
                >
                    <div class="relative">
                        <ckeditor  v-model="form.privacy_en" :config="editorConfig"></ckeditor>
                    </div>
                </FormField>
                <FormField
                    label="Terms"
                    :class="{ 'text-red-400': form.errors.privacy_en }"
                >
                    <div class="relative">
                        <ckeditor  v-model="form.terms_en" :config="editorConfig"></ckeditor>
                    </div>
                </FormField>
                <template #footer>
                    <BaseButtons>
                        <BaseButton
                            type="submit"
                            color="info"
                            label="Submit"
                            :class="{ 'opacity-25': form.processing }"
                            :disabled="form.processing"
                        />
                        <BaseButton
                            :route-name="route('dashboard')"
                            label="Cancel"
                            color="white"
                        />
                    </BaseButtons>
                </template>
            </CardBox>
        </SectionMain>
    </LayoutAuthenticated>
</template>
`

**Comment by AhmedAliGad** [comment] 2023-08-16 11:21
when I update values it returns the same values for two editors

**Comment by apoorvpal01** [comment] 2023-08-21 04:33
There are quite a few other dependencies which may be the source of the issue. The editor in itself seems to be working fine, as shown in the demo code above. You may try to diagnose the issue via the DevTools or verbose logging. The editor will be emitting the update events and listen to prop changes only for the specific variable passed to it via the `v-model`

**Comment by apoorvpal01** [comment] 2023-09-07 14:29
Closing this issue as it cannot be reproduced with the package directly and may have been caused due to other packages involved.

**Closed by apoorvpal01** 2023-09-07 14:29 UTC

**Comment by lserio** [comment] 2024-01-17 20:01
I have the same problem as @AhmedAliGad 

This is my code:


vite.config.js

```javascript
import { fileURLToPath, URL } from "node:url";
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';

export default defineConfig(({ mode }) => {
  let baseConfig = {
    plugins: [vue({
      customElement: false,
      template: {
        compilerOptions: {
        }
      }
    })],
    build: {
      lib: {
        entry: './src/wc.js',
        name: 'job-wc',
        fileName: 'job-wc'
      },
      rollupOptions: {
        external: ['vue'],
        output: {
          globals: {
            vue: 'Vue3'
          }
        }
      },
      minify: true
    },
    resolve: {
      alias: {
        "@": fileURLToPath(new URL("./src", import.meta.url)),
      },
    },
    define: {
      'process.env.NODE_ENV': JSON.stringify(import.meta.env),
    },
  };

  if (mode === 'build') {
    return Object.assign(baseConfig, {
      appType: 'custom'
    });
  }

  return baseConfig;
});
```

 main.js
```javascript
import { h, createApp } from 'vue';
import router from './router';
import CKEditor from '@mayasabha/ckeditor4-vue3';
import App from './App.vue';

createApp(App)
  .use(router)
  .use(CKEditor)
  .mount('#app');
```


Test.Vue
```vue
<template>
  <div>
    <div class="form-group">
      <label for="editor1">Editor 1</label>
      <ckeditor v-model="editor1" :config="editorConfig"></ckeditor>
    </div>

    <div class="form-group">
      <label for="editor2">Editor 2</label>
      <ckeditor v-model="editor2" :config="editorConfig"></ckeditor>
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    editorConfig: {
      language: 'en',
      height: 100,
    },
    editor1: null,
    editor2: null,
  }),
  watch: {
    'editor1': function () {
      alert('editor 1')
    },
    'editor2': function () {
      alert('editor 2')
    },
  }
};
</script>
```

and this is the result, also verified with the devtool:

![Cattura](https://github.com/mayasabha/ckeditor4-vue3/assets/61843036/d918f769-8ea4-4379-8d29-3726d7e02e6b)


What I noticed is that if I pass a different configuration to the second editor, then it works!

I hope I have been helpful.
