### ISSUE TITLE
after upgrading  to 1.0.3 from 0.0.6 "v-model" doesn't work!

### ISSUE THREAD

**Issue by nekooee** [mayasabha/ckeditor4-vue3#6] opened 2023-06-22 15:30 UTC
My project was working fine. Today I decided to upgrade your package from 0.0.6 to 1.0.3. After upgrading, I noticed that the bound value does not return anything and is empty.
I replaced the ckeditor.js file with the latest version, but it still made no difference.
My code is similar to the following code:

```js
<ckeditor :editor-url="editorUrl" v-model="editorData" :throttle="120" :config="editorConfig"></ckeditor>

<script setup>
import { computed, defineComponent, ref } from "vue";
import { component as ckeditor } from "@mayasabha/ckeditor4-vue3";

const Ckeditor = defineComponent(ckeditor);

const editorData = ref("test");

const editorUrl = "/ckeditor/ckeditor.js?v1.1";

const editorConfig = {
  FillEmptyBlocks: false,
  removePlugins: "image",
  language: "en",
  allowedContent: true,
  colorButton_enableMore: true,
  editorplaceholder: "type your text here",
  extraPlugins: ["bidi", "editorplaceholder", "justify", "panelbutton", "floatpanel", "colorbutton", "colordialog", "font", "image2", "divarea"],
  toolbar: [
    ["Source", "Maximize"],
    ["Format", "FontSize"],
    ["Bold", "Italic", "Strike"],
    ["Undo", "Redo"],
    ["RemoveFormat", "NumberedList", "BulletedList", "Outdent", "Indent"],
    ["Blockquote"],
    ["Link", "Unlink"],
    ["Image", "Table", "HorizontalRule"],
    ["BidiLtr", "BidiRtl"],
    ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"],
    ["TextColor", "BGColor"],
  ],
  contentsCss: "/ckeditor/custom.css?v=1.4",
};
</script>

```

What is the problem that v-model no longer works for me and neither takes nor returns anything?

**Comment by apoorvpal01** [comment] 2023-06-22 16:18
Can you try removing the line 7 from your code and attempting to run the application again? The `defineComponent` syntax is not required as the imported `component as ckeditor` is already a valid Vue component.

**Comment by apoorvpal01** [comment] 2023-06-22 17:47
Can you confirm if it works without specifying the `editorUrl` prop?

**Comment by nekooee** [comment] 2023-06-22 18:16
> Can you confirm if it works without specifying the `editorUrl` prop?

Yes, I tested it and it still doesn't work after removing the `editorUrl`.

**Comment by apoorvpal01** [comment] 2023-06-23 04:22
Please check if the issue is fixed now. There were certain issues which were happening due to incorrect ES6 build, which should be fixed with the update

**Comment by apoorvpal01** [comment] 2023-06-24 02:53
@nekooee After further testing, the ES6 imports were not found as the cause. I am still unable to replicate the issue on a sample Vue app. Please setup a repository to replicate the issue, as it may be specific to the customized config.js file or plugins.

**Comment by nekooee** [comment] 2023-06-24 12:19
> @nekooee After further testing, the ES6 imports were not found as the cause. I am still unable to replicate the issue on a sample Vue app. Please setup a repository to replicate the issue, as it may be specific to the customized config.js file or plugins.

@apoorvpal01  Hello. Thank you for taking the time to solve my problem. I first created a new raw project but there was no such problem! I tried to install all the dependencies of the main project here as well. But still no problem.
I still could not understand why this problem occurs in the main project. If I get more information I will share it with you.
Thank you again.

**Comment by nekooee** [comment] 2023-06-24 16:13
I deleted the folder node-module and .yarn. After I ran `yarn install` fortunately the problem was solved. I don't know what the problem was.

**Comment by apoorvpal01** [comment] 2023-06-25 02:01
It must have been related to the local cache in that case. Thanks for the update. I am closing this issue now.

**Closed by apoorvpal01** 2023-06-25 02:01 UTC
Labels: bug

**Comment by nekooee** [comment] 2023-10-10 19:03
I downgraded and upgraded again, the problem was solved by itself. I think there is a problem in this package that occurs every time when it is updated. I try not to update anymore so that I don't have to

**Comment by apoorvpal01** [comment] 2023-10-11 03:55
That seems quite odd. The package manager would update the source code for the package completely so there shouldn't really be any difference between updating it and getting the latest version installed directly. I will try to find if this is a reported issue somewhere and if there's something I can do on the package to fix it. Thanks for informing me @nekooee
